<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Filesystem\Filesystem;
use ReflectionEnum;
use ReflectionMethod;

class GenerateTypescriptEnums extends Command
{
    protected $signature = 'enum:typescript {--output= : Output directory for generated files}';

    protected $description = 'Generate TypeScript files from PHP string-backed enums';

    public function __construct(private Filesystem $files)
    {
        parent::__construct();
    }

    public function handle(): int
    {
        $enumsPath = app_path('Enums');
        $outputPath = $this->option('output') ?: resource_path('js/enums');

        if (! $this->files->isDirectory($enumsPath)) {
            $this->error('No Enums directory found at app/Enums.');

            return self::FAILURE;
        }

        $this->files->ensureDirectoryExists($outputPath);

        $enumFiles = $this->files->glob($enumsPath.'/*.php');
        $generatedEnums = [];

        foreach ($enumFiles as $file) {
            $enumClass = 'App\\Enums\\'.pathinfo($file, PATHINFO_FILENAME);

            if (! enum_exists($enumClass)) {
                continue;
            }

            $reflection = new ReflectionEnum($enumClass);

            if (! $reflection->isBacked() || (string) $reflection->getBackingType() !== 'string') {
                continue;
            }

            $enumName = $reflection->getShortName();
            $typescript = $this->generateTypescript($reflection, $enumName);

            $this->files->put($outputPath.'/'.$enumName.'.ts', $typescript);
            $generatedEnums[] = $enumName;

            $this->components->info("Generated {$enumName}.ts");
        }

        if (empty($generatedEnums)) {
            $this->components->warn('No string-backed enums found.');

            return self::SUCCESS;
        }

        $this->generateIndex($outputPath, $generatedEnums);
        $this->components->info('Generated index.ts');

        return self::SUCCESS;
    }

    private function generateTypescript(ReflectionEnum $reflection, string $enumName): string
    {
        $cases = $reflection->getCases();
        $hasLabels = $reflection->hasMethod('label') && ! (new ReflectionMethod($reflection->getName(), 'label'))->isStatic();

        $lines = [
            '// This file is auto-generated by `php artisan enum:typescript`',
            '// Do not edit manually.',
            '',
        ];

        // Const object
        $lines[] = "export const {$enumName} = {";
        foreach ($cases as $case) {
            $lines[] = "    {$case->getName()}: '{$case->getBackingValue()}',";
        }
        $lines[] = '} as const;';
        $lines[] = '';

        // Union type
        $lines[] = "export type {$enumName} = (typeof {$enumName})[keyof typeof {$enumName}];";

        // Labels map
        if ($hasLabels) {
            $lines[] = '';
            $lines[] = "export const {$enumName}Label: Record<{$enumName}, string> = {";
            foreach ($cases as $case) {
                $enumInstance = $reflection->getName()::from($case->getBackingValue());
                $label = $this->escapeQuotes($enumInstance->label());
                $lines[] = "    '{$case->getBackingValue()}': '{$label}',";
            }
            $lines[] = '};';
        }

        $lines[] = '';

        return implode("\n", $lines);
    }

    private function generateIndex(string $outputPath, array $enumNames): void
    {
        $lines = [
            '// This file is auto-generated by `php artisan enum:typescript`',
            '// Do not edit manually.',
            '',
        ];

        sort($enumNames);

        foreach ($enumNames as $name) {
            $lines[] = "export * from './{$name}';";
        }

        $lines[] = '';

        $this->files->put($outputPath.'/index.ts', implode("\n", $lines));
    }

    private function escapeQuotes(string $value): string
    {
        return str_replace("'", "\\'", $value);
    }
}
