<?php

use App\Models\Service;
use App\Models\User;
use App\Models\Vehicle;
use Laravel\Dusk\Browser;
use Spatie\Activitylog\Models\Activity;
use Spatie\Permission\Models\Role as SpatieRole;

beforeEach(function (): void {
    $this->artisan('migrate:fresh', ['--no-interaction' => true]);
});

function auditLogAuthenticateAsSuperAdmin(): User
{
    $role = SpatieRole::firstOrCreate(['name' => 'super_admin', 'guard_name' => 'web']);
    $user = User::where('email', env('SUPER_ADMIN_USER'))->first();
    if (! $user) {
        $user = User::factory()->create([
            'email' => env('SUPER_ADMIN_USER'),
            'password' => bcrypt(env('SUPER_ADMIN_PASSWORD')),
        ]);
    }
    $user->assignRole($role);

    return $user;
}

function auditLogAuthenticateAsOperator(): User
{
    $role = SpatieRole::firstOrCreate(['name' => 'operator', 'guard_name' => 'web']);
    $user = User::factory()->create([
        'email' => 'operator-dusk@sgte.app',
        'password' => bcrypt('password'),
    ]);
    $user->assignRole($role);

    return $user;
}

function auditLogSeedBaseline(User $admin): array
{
    // Two contrasting activity entries: one marked as an executed-day edit
    // (amber tint expected), one a plain Vehicle model activity.
    $service = Service::factory()->create();
    $vehicle = Vehicle::factory()->create(['plate' => 'DSK01']);

    Activity::query()->delete();

    activity()
        ->performedOn($service)
        ->causedBy($admin)
        ->event('updated')
        ->withProperties([
            'justification' => 'Prueba Dusk — justificación REQ-009 AC#10.',
            'edited_on_executed_day' => true,
            'attributes' => ['unit_value' => 150000],
            'old' => ['unit_value' => 100000],
        ])
        ->log('Servicio editado en día ejecutado');

    activity()
        ->performedOn($vehicle)
        ->causedBy($admin)
        ->event('created')
        ->log('Vehículo creado');

    return compact('service', 'vehicle');
}

test('admin sees the audit log index with filter bar and key columns', function (): void {
    $admin = auditLogAuthenticateAsSuperAdmin();
    auditLogSeedBaseline($admin);

    $this->browse(function (Browser $browser) use ($admin): void {
        $browser->loginAs($admin)
            ->visit('/audit-log')
            ->waitForText('Auditoría')
            ->assertSee('Fecha')
            ->assertSee('Usuario')
            ->assertSee('Acción')
            ->assertSee('Entidad')
            ->assertSee('Descripción')
            ->assertSee('Justificación')
            ->assertSee('Desde')
            ->assertSee('Hasta')
            ->assertSee('Servicio editado en día ejecutado')
            ->assertSee('Vehículo creado')
            ->assertDontSee('auto-generated by Blueprint')
            ->screenshot('audit-log-index-admin');
    });
});

test('admin filters audit log by subject_type = Servicio', function (): void {
    $admin = auditLogAuthenticateAsSuperAdmin();
    auditLogSeedBaseline($admin);

    $this->browse(function (Browser $browser): void {
        $browser->visit('/audit-log?filter[subject_type]='.urlencode(Service::class))
            ->waitForText('Auditoría')
            ->assertSee('Servicio editado en día ejecutado')
            ->assertDontSee('Vehículo creado')
            ->screenshot('audit-log-subject-type-filter');
    });
});

test('admin opens detail sheet and reads the justification', function (): void {
    $admin = auditLogAuthenticateAsSuperAdmin();
    auditLogSeedBaseline($admin);

    $this->browse(function (Browser $browser) use ($admin): void {
        $browser->loginAs($admin)
            ->visit('/audit-log')
            ->waitForText('Auditoría')
            ->waitForText('Servicio editado en día ejecutado')
            // The "Ver detalles" Eye button is the only aria-label="Ver detalles" button in the row
            ->click('button[aria-label="Ver detalles"]')
            ->waitForText('Prueba Dusk')
            ->assertSee('Prueba Dusk — justificación REQ-009 AC#10.')
            ->screenshot('audit-log-detail-sheet-justification');
    });
});

test('operator receives 403 on audit-log', function (): void {
    $operator = auditLogAuthenticateAsOperator();

    $this->browse(function (Browser $browser) use ($operator): void {
        $browser->loginAs($operator)
            ->visit('/audit-log')
            ->assertSee('403')
            ->screenshot('audit-log-operator-403');
    });
});
