<?php

use App\Models\Contract;
use App\Models\Driver;
use App\Models\Service;
use App\Models\ThirdParty;
use App\Models\User;
use App\Models\Vehicle;
use Illuminate\Support\Carbon;
use Laravel\Dusk\Browser;
use Spatie\Permission\Models\Role as SpatieRole;

beforeEach(function (): void {
    $this->artisan('migrate:fresh', ['--no-interaction' => true]);
});

function contractsAuthenticateAsSuperAdmin(): User
{
    $role = SpatieRole::firstOrCreate(['name' => 'super_admin', 'guard_name' => 'web']);
    $user = User::where('email', env('SUPER_ADMIN_USER'))->first();
    if (! $user) {
        $user = User::factory()->create([
            'email' => env('SUPER_ADMIN_USER'),
            'password' => bcrypt(env('SUPER_ADMIN_PASSWORD')),
        ]);
    }
    $user->assignRole($role);

    return $user;
}

test('contracts index renders the table with Spanish headers and four-state filter', function (): void {
    $user = contractsAuthenticateAsSuperAdmin();

    $customer = ThirdParty::factory()->create([
        'is_natural_person' => false,
        'company_name' => 'Transp. DuskTest S.A.',
        'is_customer' => true,
    ]);

    $vigente = Contract::factory()->create([
        'contract_number' => 'CT-VIGENTE-DUSK',
        'third_party_id' => $customer->id,
        'active' => true,
        'start_date' => Carbon::today()->subMonth(),
        'end_date' => Carbon::today()->addMonths(6),
    ]);
    $vencido = Contract::factory()->create([
        'contract_number' => 'CT-VENCIDO-DUSK',
        'third_party_id' => $customer->id,
        'active' => true,
        'start_date' => Carbon::today()->subMonths(6),
        'end_date' => Carbon::today()->subDays(10),
    ]);

    $this->browse(function (Browser $browser) use ($user, $vigente, $vencido): void {
        $browser->loginAs($user)
            ->visit('/contracts')
            ->waitForText('Contratos')
            ->assertSee('Número')
            ->assertSee('Cliente')
            ->assertSee('Objeto')
            ->assertSee('Vigencia')
            ->assertSee('Estado')
            ->assertSee($vigente->contract_number)
            ->assertSee($vencido->contract_number)
            ->assertDontSee('auto-generated by Blueprint')
            ->screenshot('contracts-index-rendered');

        // Apply the vencido filter — only the expired contract remains
        $browser->visit('/contracts?filter[contract_status]=vencido')
            ->waitForText('Contratos')
            ->assertSee($vencido->contract_number)
            ->assertDontSee($vigente->contract_number)
            ->assertSee('Vencido')
            ->screenshot('contracts-index-vencido-filter');
    });
});

test('contracts show page renders the five cards including recent services', function (): void {
    $user = contractsAuthenticateAsSuperAdmin();

    $customer = ThirdParty::factory()->create([
        'is_natural_person' => false,
        'company_name' => 'Cliente ShowTest S.A.',
        'is_customer' => true,
    ]);
    $contract = Contract::factory()->create([
        'contract_number' => 'CT-SHOW-001',
        'third_party_id' => $customer->id,
        'active' => true,
        'start_date' => Carbon::today()->subMonth(),
        'end_date' => Carbon::today()->addMonths(3),
        'route_description' => 'Ruta de prueba Medellín ↔ Bogotá.',
    ]);

    $vehicle = Vehicle::factory()->create();
    $driver = Driver::factory()->create();
    Service::factory()->count(3)->create([
        'contract_id' => $contract->id,
        'vehicle_id' => $vehicle->id,
        'driver_id' => $driver->id,
    ]);

    $this->browse(function (Browser $browser) use ($user, $contract, $customer): void {
        $browser->loginAs($user)
            ->visit("/contracts/{$contract->id}")
            ->waitForText($contract->contract_number)
            ->assertSee('Datos del Contrato')
            ->assertSee('Cliente')
            ->assertSee('Vigencia')
            ->assertSee('Servicios Recientes')
            ->assertSee($customer->company_name)
            ->assertSee('Ver tercero')
            ->assertSee('Ruta de prueba Medellín')
            ->assertDontSee('auto-generated by Blueprint')
            ->screenshot('contracts-show-five-cards');
    });
});

test('contracts create dialog auto-generates contract_number when is_generic is true', function (): void {
    $user = contractsAuthenticateAsSuperAdmin();

    $customer = ThirdParty::factory()->create([
        'is_natural_person' => false,
        'company_name' => 'Cliente Genérico S.A.',
        'is_customer' => true,
    ]);

    $this->browse(function (Browser $browser) use ($user): void {
        $browser->loginAs($user)
            ->visit('/contracts')
            ->waitForText('Contratos')
            ->press('Crear Contrato')
            ->waitForText('Crear Contrato')
            ->assertSee('Número de Contrato')
            ->assertSee('Cliente')
            ->assertDontSee('Se generará automáticamente')
            ->screenshot('contracts-create-dialog-open');

        // Toggle the is_generic switch — verify the Input is replaced
        // with the auto-generation note.
        $browser->click('#dlg_is_generic')
            ->waitForText('Se generará automáticamente al guardar')
            ->assertSee('(GEN-####-YYYY)')
            ->screenshot('contracts-create-dialog-generic-on');
    });

    // Backend sanity check: the auto-generation logic still creates a
    // GEN-####-YYYY contract when store() is hit directly. This pins
    // the load-bearing controller logic.
    $this->actingAs($user)->post(route('contracts.store'), [
        'third_party_id' => $customer->id,
        'contract_object' => 'business',
        'start_date' => Carbon::today()->toDateString(),
        'end_date' => Carbon::today()->addYear()->toDateString(),
        'route_description' => 'Dusk generic contract.',
        'is_generic' => true,
        'active' => true,
    ]);

    $generic = Contract::query()->where('is_generic', true)->latest('id')->first();
    expect($generic)->not->toBeNull();
    expect($generic->contract_number)->toStartWith('GEN-');
});

test('third-party show Contratos card link lands on the rebuilt contract show page', function (): void {
    $user = contractsAuthenticateAsSuperAdmin();

    $customer = ThirdParty::factory()->create([
        'is_natural_person' => false,
        'company_name' => 'Cliente Link S.A.',
        'is_customer' => true,
        'is_provider' => false,
    ]);
    $contract = Contract::factory()->create([
        'contract_number' => 'CT-LINK-001',
        'third_party_id' => $customer->id,
        'active' => true,
        'start_date' => Carbon::today()->subMonth(),
        'end_date' => Carbon::today()->addMonths(6),
    ]);

    $this->browse(function (Browser $browser) use ($user, $contract, $customer): void {
        $browser->loginAs($user)
            ->visit("/third-parties/{$customer->id}")
            ->waitForText($customer->company_name)
            ->assertSee('Contratos')
            ->assertSee($contract->contract_number)
            ->visit("/contracts/{$contract->id}")
            ->waitForText($contract->contract_number)
            ->assertPathIs("/contracts/{$contract->id}")
            ->assertSee('Datos del Contrato')
            ->assertDontSee('auto-generated by Blueprint')
            ->screenshot('third-party-to-contract-cross-link');
    });
});

test('nested create-client dialog submit does not submit the contract form (BUG-002)', function (): void {
    $user = contractsAuthenticateAsSuperAdmin();

    $this->browse(function (Browser $browser) use ($user): void {
        $browser->loginAs($user)
            ->visit('/contracts')
            ->waitForText('Contratos')
            ->press('Crear Contrato')
            ->waitForText('Crear Contrato')
            ->click('button[aria-label="Crear nuevo cliente"]')
            ->waitForText('Crear Tercero')
            // Submit the nested "Crear Tercero" dialog with an empty form. It
            // must stay open showing its own validation — the contract <form>
            // behind it must NOT submit (which would reload the page and close
            // both dialogs). Radix marks the backgrounded dialog aria-hidden,
            // so :not([aria-hidden="true"]) targets the active nested dialog.
            ->within('[role=dialog]:not([aria-hidden="true"])', function (Browser $dialog): void {
                $dialog->press('Guardar');
            })
            ->pause(1500)
            ->assertSee('Crear Tercero')
            ->assertSee('Número de Identificación');
    });
});
