<?php

use App\Models\Driver;
use App\Models\Municipality;
use App\Models\Service;
use App\Models\User;
use Illuminate\Support\Carbon;
use Laravel\Dusk\Browser;
use Spatie\Permission\Models\Role as SpatieRole;

beforeEach(function (): void {
    // We bring up only the schema + the catalog data migration.
    // The operational seeders have idempotent fixture setup we build
    // per-test below; running --seed needlessly runs ContractSeeder etc.
    $this->artisan('migrate:fresh', ['--no-interaction' => true]);
});

function driversAuthenticateAsSuperAdmin(): User
{
    $role = SpatieRole::firstOrCreate(['name' => 'super_admin', 'guard_name' => 'web']);
    $user = User::where('email', env('SUPER_ADMIN_USER'))->first();
    if (! $user) {
        $user = User::factory()->create([
            'email' => env('SUPER_ADMIN_USER'),
            'password' => bcrypt(env('SUPER_ADMIN_PASSWORD')),
        ]);
    }
    $user->assignRole($role);

    return $user;
}

/**
 * Seeds three drivers in mixed license-expiry states so the
 * license_status filter has something meaningful to filter on.
 *
 * @return array{expired: Driver, expiring: Driver, ok: Driver}
 */
function driversSeedMixedExpiry(): array
{
    $today = Carbon::today();

    $expired = Driver::factory()->create([
        'first_name' => 'Pedro',
        'first_lastname' => 'Vencido',
        'license_due_date' => $today->copy()->subDay(),
    ]);

    $expiring = Driver::factory()->create([
        'first_name' => 'María',
        'first_lastname' => 'Pendiente',
        'license_due_date' => $today->copy()->addDays(15),
    ]);

    $ok = Driver::factory()->create([
        'first_name' => 'Juan',
        'first_lastname' => 'AlDía',
        'license_due_date' => $today->copy()->addYear(),
    ]);

    return ['expired' => $expired, 'expiring' => $expiring, 'ok' => $ok];
}

test('drivers index renders the table with Spanish headers and expected rows', function (): void {
    $user = driversAuthenticateAsSuperAdmin();
    $drivers = driversSeedMixedExpiry();

    $this->browse(function (Browser $browser) use ($user, $drivers): void {
        $browser->loginAs($user)
            ->visit('/drivers')
            ->waitForText('Conductores')
            ->assertSee('Conductores')
            ->assertSee('Documento')
            ->assertSee('Nombre')
            ->assertSee('Categoría')
            ->assertSee('Licencia')
            ->assertSee('Seg. Social')
            ->assertSee('Vinculación')
            ->assertSee($drivers['expired']->first_lastname)
            ->assertSee($drivers['expiring']->first_lastname)
            ->assertSee($drivers['ok']->first_lastname)
            ->assertDontSee('Drivers Index')
            ->assertDontSee('auto-generated by Blueprint')
            ->screenshot('drivers-index-rendered');
    });
});

test('drivers index license_status=expired filter narrows to expired rows', function (): void {
    $user = driversAuthenticateAsSuperAdmin();
    $drivers = driversSeedMixedExpiry();

    $this->browse(function (Browser $browser) use ($user, $drivers): void {
        $browser->loginAs($user)
            ->visit('/drivers?filter[license_status]=expired')
            ->waitForText('Conductores')
            ->assertSee($drivers['expired']->first_lastname)
            ->assertDontSee($drivers['expiring']->first_lastname)
            ->assertDontSee($drivers['ok']->first_lastname)
            ->screenshot('drivers-index-filtered-expired');
    });
});

test('dashboard alert row links into the filtered drivers index', function (): void {
    $user = driversAuthenticateAsSuperAdmin();
    $drivers = driversSeedMixedExpiry();

    $this->browse(function (Browser $browser) use ($user, $drivers): void {
        $expectedSubject = trim(
            $drivers['expired']->first_name.' '.$drivers['expired']->first_lastname,
        );

        $browser->loginAs($user)
            ->visit('/dashboard')
            ->waitForText('Alertas de documentos')
            ->assertSee('Alertas de documentos')
            ->assertSee($expectedSubject)
            ->screenshot('dashboard-with-driver-alerts')
            ->clickLink($expectedSubject)
            ->waitForLocation('/drivers')
            ->assertPathIs('/drivers');

        // assertQueryStringHas can't parse Laravel's bracket notation
        // (parse_str expansion). Read driver->getCurrentURL() and
        // assert the substring is present.
        $currentUrl = $browser->driver->getCurrentURL();
        expect($currentUrl)
            ->toContain('filter')
            ->toContain('license_status')
            ->toContain('expired');

        $browser
            ->assertSee($drivers['expired']->first_lastname)
            ->assertDontSee($drivers['ok']->first_lastname)
            ->screenshot('drivers-after-dashboard-cross-link');
    });
});

test('driver show page renders five cards with rich data', function (): void {
    $user = driversAuthenticateAsSuperAdmin();

    $municipality = Municipality::factory()->create();
    $linkedUser = User::factory()->create(['email' => 'driver-linked@example.test']);
    $driver = Driver::factory()->create([
        'first_name' => 'Carlos',
        'first_lastname' => 'Demuestra',
        'municipality_id' => $municipality->id,
        'user_id' => $linkedUser->id,
        'license_due_date' => Carbon::today()->addMonths(6),
    ]);

    Service::factory()->count(5)->create([
        'driver_id' => $driver->id,
    ]);

    $this->browse(function (Browser $browser) use ($user, $driver): void {
        $browser->loginAs($user)
            ->visit("/drivers/{$driver->id}")
            ->waitForText($driver->first_lastname)
            ->assertSee($driver->first_lastname)
            ->assertSee('Información Personal')
            ->assertSee('Licencia y Seguridad Social')
            ->assertSee('Afiliaciones')
            ->assertSee('Servicios Recientes')
            ->assertSee('Cuenta de acceso:')
            ->assertSee('driver-linked@example.test')
            ->assertDontSee('auto-generated by Blueprint')
            ->screenshot('driver-show-rendered');
    });
});

test('admin opens the create modal and sees the form sections', function (): void {
    $user = driversAuthenticateAsSuperAdmin();
    Municipality::factory()->create();

    $this->browse(function (Browser $browser) use ($user): void {
        $browser->loginAs($user)
            ->visit('/drivers')
            ->waitForText('Conductores')
            ->press('Crear Conductor')
            ->waitForText('Complete los campos para registrar un nuevo conductor')
            ->assertSee('Crear Conductor')
            ->assertSee('Identificación')
            ->assertSee('Datos de Contacto')
            ->assertSee('Licencia')
            ->assertSee('Afiliaciones')
            ->assertSee('Estado')
            ->assertSee('Primer Nombre')
            ->assertSee('Categoría')
            ->screenshot('drivers-create-modal-open');

        // Field-typing through Radix Select + MunicipalityCombobox is
        // brittle; the persistence path is fully covered by
        // DriverControllerTest::test_store_saves_and_redirects (Pest).
    });
});
