<?php

use App\Models\Contract;
use App\Models\Driver;
use App\Models\Fuec;
use App\Models\FuecNumberRange;
use App\Models\Service;
use App\Models\ThirdParty;
use App\Models\User;
use App\Models\Vehicle;
use Laravel\Dusk\Browser;
use Spatie\Permission\Models\Role as SpatieRole;

beforeEach(function (): void {
    $this->artisan('migrate:fresh', ['--no-interaction' => true]);
    config()->set('sgte.fuec_enabled', true);
});

function fuecAuthenticateAsSuperAdmin(): User
{
    $role = SpatieRole::firstOrCreate(['name' => 'super_admin', 'guard_name' => 'web']);
    $user = User::where('email', env('SUPER_ADMIN_USER'))->first();
    if (! $user) {
        $user = User::factory()->create([
            'email' => env('SUPER_ADMIN_USER'),
            'password' => bcrypt(env('SUPER_ADMIN_PASSWORD')),
        ]);
    }
    $user->assignRole($role);

    return $user;
}

function fuecUserWithRole(string $roleName): User
{
    $role = SpatieRole::firstOrCreate(['name' => $roleName, 'guard_name' => 'web']);
    $user = User::factory()->create();
    $user->assignRole($role);

    return $user;
}

function fuecSeedSampleRow(): Fuec
{
    $customer = ThirdParty::factory()->create([
        'is_customer' => true,
        'is_natural_person' => false,
        'company_name' => 'Cliente FUEC Dusk S.A.',
    ]);
    $contract = Contract::factory()->create([
        'third_party_id' => $customer->id,
        'contract_number' => 'CT-FUEC-DUSK-001',
    ]);
    $vehicle = Vehicle::factory()->create(['plate' => 'DSK99']);
    $driver = Driver::factory()->create([
        'first_name' => 'Ana',
        'first_lastname' => 'Martínez',
    ]);
    $service = Service::factory()->create([
        'contract_id' => $contract->id,
        'vehicle_id' => $vehicle->id,
        'driver_id' => $driver->id,
    ]);
    $range = FuecNumberRange::factory()->active()->create([
        'resolution_number' => 'RES-DUSK',
        'resolution_year' => 2026,
        'range_from' => 5000,
        'range_to' => 5100,
    ]);

    return Fuec::factory()->create([
        'service_id' => $service->id,
        'fuec_number_range_id' => $range->id,
        'consecutive_number' => 5001,
        'status' => 'active',
    ]);
}

test('admin sees the FUEC index with Spanish headers and Generar FUEC button', function (): void {
    $user = fuecAuthenticateAsSuperAdmin();
    fuecSeedSampleRow();

    $this->browse(function (Browser $browser) use ($user): void {
        $browser->loginAs($user)
            ->visit('/fuecs')
            ->waitForText('FUEC')
            ->assertSee('Consecutivo')
            ->assertSee('Servicio')
            ->assertSee('Vehículo')
            ->assertSee('Conductor')
            ->assertSee('Estado')
            ->assertSee('DSK99')
            ->assertSee('Ana Martínez')
            ->assertSee('Vigente')
            ->assertSee('Generar FUEC')
            ->assertDontSee('auto-generated by Blueprint')
            ->screenshot('fuec-index-admin');
    });
});

test('admin sees the FUEC show page with Servicio + QR verification cards', function (): void {
    $user = fuecAuthenticateAsSuperAdmin();
    $fuec = fuecSeedSampleRow();

    $this->browse(function (Browser $browser) use ($user, $fuec): void {
        $browser->loginAs($user)
            ->visit("/fuecs/{$fuec->id}")
            ->waitForText("FUEC Nº {$fuec->consecutive_number}")
            ->assertSee('Resolución RES-DUSK de 2026')
            ->assertSee('Vigente')
            ->assertSee('Descargar PDF')
            ->assertSee('Anular')
            ->assertSee('Servicio')
            ->assertSee('CT-FUEC-DUSK-001')
            ->assertSee('DSK99')
            ->assertSee('Ana Martínez')
            ->assertSee('QR de verificación')
            ->assertSee("/fuec/verify/{$fuec->uuid}")
            ->assertDontSee('auto-generated by Blueprint')
            ->screenshot('fuec-show-admin');
    });
});

test('admin reaches the Generar FUEC create page with the pre-gen validation alert', function (): void {
    $user = fuecAuthenticateAsSuperAdmin();

    $this->browse(function (Browser $browser) use ($user): void {
        $browser->loginAs($user)
            ->visit('/fuecs/create')
            ->waitForText('Generar FUEC')
            ->assertSee('Validaciones previas')
            ->assertSee('contrato esté vigente')
            ->assertSee('documentos del vehículo')
            ->assertSee('licencia del conductor')
            ->assertSee('rango MinTransporte activo')
            ->screenshot('fuec-create-admin');
    });
});

test('admin can view the FUEC number ranges admin page', function (): void {
    $user = fuecAuthenticateAsSuperAdmin();
    FuecNumberRange::factory()->active()->create([
        'resolution_number' => 'RES-RANGO-DUSK',
        'resolution_year' => 2026,
        'range_from' => 1000,
        'range_to' => 9999,
    ]);

    $this->browse(function (Browser $browser) use ($user): void {
        $browser->loginAs($user)
            ->visit('/fuec-number-ranges')
            ->waitForText('Rangos MinTransporte')
            ->assertSee('Resolución')
            ->assertSee('Año')
            ->assertSee('RES-RANGO-DUSK')
            ->assertSee('Nuevo rango')
            ->screenshot('fuec-number-ranges-admin');
    });
});

test('operator cannot see the FUEC section (no VIEW_FUEC permission)', function (): void {
    $user = fuecUserWithRole('operator');
    fuecSeedSampleRow();

    $this->browse(function (Browser $browser) use ($user): void {
        $browser->loginAs($user)
            ->visit('/fuecs')
            ->assertSourceMissing('Documentos FUEC')
            ->screenshot('fuec-index-operator-denied');
    });
});
