<?php

use App\Enums\ServiceStatus;
use App\Models\Driver;
use App\Models\Service;
use App\Models\User;
use App\Models\Vehicle;
use App\Models\VehicleLocation;
use Illuminate\Support\Carbon;
use Laravel\Dusk\Browser;
use Spatie\Permission\Models\Role as SpatieRole;

beforeEach(function (): void {
    $this->artisan('migrate:fresh', ['--no-interaction' => true]);
    config()->set('sgte.gps_enabled', true);
});

function gpsAuthenticateAsSuperAdmin(): User
{
    $role = SpatieRole::firstOrCreate(['name' => 'super_admin', 'guard_name' => 'web']);
    $user = User::where('email', env('SUPER_ADMIN_USER'))->first();
    if (! $user) {
        $user = User::factory()->create([
            'email' => env('SUPER_ADMIN_USER'),
            'password' => bcrypt(env('SUPER_ADMIN_PASSWORD')),
        ]);
    }
    $user->assignRole($role);

    return $user;
}

function gpsUserWithRole(string $roleName): User
{
    $role = SpatieRole::firstOrCreate(['name' => $roleName, 'guard_name' => 'web']);
    $user = User::factory()->create();
    $user->assignRole($role);

    return $user;
}

function gpsSeedActiveServiceWithLocation(): Service
{
    $vehicle = Vehicle::factory()->create(['plate' => 'GPS99']);
    $driver = Driver::factory()->create([
        'first_name' => 'Juan',
        'first_lastname' => 'Gómez',
    ]);
    $service = Service::factory()->create([
        'vehicle_id' => $vehicle->id,
        'driver_id' => $driver->id,
        'service_status' => ServiceStatus::Open,
        'service_date' => Carbon::today()->toDateString(),
    ]);
    VehicleLocation::factory()->gps()->create([
        'service_id' => $service->id,
        'vehicle_id' => $vehicle->id,
        'recorded_at' => Carbon::now(),
        'latitude' => 6.2518,
        'longitude' => -75.5636,
        'accuracy' => 10.0,
    ]);

    return $service;
}

test('admin sees the /gps/map page with the Leaflet container + OpenStreetMap attribution', function (): void {
    $user = gpsAuthenticateAsSuperAdmin();
    gpsSeedActiveServiceWithLocation();

    $this->browse(function (Browser $browser) use ($user): void {
        $browser->loginAs($user)
            ->visit('/gps/map')
            ->waitForText('Mapa')
            ->assertSee('GPS')
            // Refresh interval text anchor — pins the interval copy on the
            // page. REFRESH_INTERVAL_MS = 300_000 → "5 min".
            ->assertSee('5 min')
            ->assertSee('servicios activos')
            // Leaflet always renders OSM attribution inside the map.
            ->waitForText('OpenStreetMap', 10)
            ->assertDontSee('auto-generated by Blueprint')
            ->screenshot('gps-map-admin');
    });
});

test('operator can view the /gps/map page', function (): void {
    $user = gpsUserWithRole('operator');

    $this->browse(function (Browser $browser) use ($user): void {
        $browser->loginAs($user)
            ->visit('/gps/map')
            ->waitForText('Mapa')
            ->assertSee('servicios activos')
            ->screenshot('gps-map-operator');
    });
});

test('driver receives 403 on /gps/map', function (): void {
    $user = gpsUserWithRole('driver');

    $this->browse(function (Browser $browser) use ($user): void {
        $browser->loginAs($user)
            ->visit('/gps/map')
            ->assertSourceMissing('OpenStreetMap')
            ->assertSourceMissing('servicios activos')
            ->screenshot('gps-map-driver-denied');
    });
});

test('accounting receives 403 on /gps/map', function (): void {
    $user = gpsUserWithRole('accounting');

    $this->browse(function (Browser $browser) use ($user): void {
        $browser->loginAs($user)
            ->visit('/gps/map')
            ->assertSourceMissing('OpenStreetMap')
            ->assertSourceMissing('servicios activos')
            ->screenshot('gps-map-accounting-denied');
    });
});

// Flag-off 404s are covered by VehicleLocationMapControllerTest (Pest).
// Toggling config at the Dusk HTTP boundary isn't supported without
// restarting the stack, so this assertion stays in Pest where it works.

test('gps map auto-refresh does not throw ViewTransition errors when tab is hidden (F-010 regression)', function (): void {
    $user = gpsAuthenticateAsSuperAdmin();
    gpsSeedActiveServiceWithLocation();

    $this->browse(function (Browser $browser) use ($user): void {
        $browser->loginAs($user)
            ->visit('/gps/map')
            ->waitForText('Mapa')
            // Flip the document into "hidden" state so the refresh
            // interval hits the branch that previously threw.
            ->script(<<<'JS'
                Object.defineProperty(document, 'visibilityState', { configurable: true, get: () => 'hidden' });
                Object.defineProperty(document, 'hidden', { configurable: true, get: () => true });
                document.dispatchEvent(new Event('visibilitychange'));
                window.__auditRefreshErrors = [];
                window.addEventListener('unhandledrejection', (e) => {
                    window.__auditRefreshErrors.push(String(e.reason));
                });
            JS
            );

        // Fast-path: poke the refresh tick without waiting 30s.
        $browser->script('window.dispatchEvent(new Event("focus"));');
        $browser->pause(1500);

        $errors = $browser->script('return window.__auditRefreshErrors ?? [];')[0];

        expect($errors)->toBeArray();
        foreach ($errors as $message) {
            expect($message)->not->toContain('Skipped ViewTransition due to document being hidden');
        }

        $browser->screenshot('audit-F-010-gps-map-no-refresh-when-hidden');
    });
});

test('admin sees the /vehicle-locations index with Spanish headers + Manual/GPS badges', function (): void {
    $user = gpsAuthenticateAsSuperAdmin();
    gpsSeedActiveServiceWithLocation();

    $this->browse(function (Browser $browser) use ($user): void {
        $browser->loginAs($user)
            ->visit('/vehicle-locations')
            ->waitForText('Ubicaciones')
            ->assertSee('Vehículo')
            ->assertSee('Fecha/Hora')
            ->assertSee('Coordenadas')
            ->assertSee('Precisión')
            ->assertSee('Registrado por')
            ->assertSee('GPS99')
            ->assertSee('GPS')
            ->screenshot('vehicle-locations-index-admin');
    });
});
