<?php

use App\Enums\PaymentStatus;
use App\Models\Invoice;
use App\Models\ThirdParty;
use App\Models\User;
use Illuminate\Support\Carbon;
use Laravel\Dusk\Browser;
use Spatie\Permission\Models\Role as SpatieRole;

beforeEach(function (): void {
    // migrate:fresh runs the seed_catalog_data migration, which
    // creates all 5 spatie roles (super_admin, admin, operator,
    // driver, accounting) and wires their permission grants. Tests
    // can then assign roles to factory users directly.
    $this->artisan('migrate:fresh', ['--no-interaction' => true]);
});

function invoicesAuthenticateAsSuperAdmin(): User
{
    $role = SpatieRole::firstOrCreate(['name' => 'super_admin', 'guard_name' => 'web']);
    $user = User::where('email', env('SUPER_ADMIN_USER'))->first();
    if (! $user) {
        $user = User::factory()->create([
            'email' => env('SUPER_ADMIN_USER'),
            'password' => bcrypt(env('SUPER_ADMIN_PASSWORD')),
        ]);
    }
    $user->assignRole($role);

    return $user;
}

function invoicesUserWithRole(string $roleName): User
{
    $role = SpatieRole::firstOrCreate(['name' => $roleName, 'guard_name' => 'web']);
    $user = User::factory()->create();
    $user->assignRole($role);

    return $user;
}

test('invoices index renders with Spanish headers, overdue filter, and row tint', function (): void {
    $user = invoicesAuthenticateAsSuperAdmin();

    $customer = ThirdParty::factory()->create([
        'is_natural_person' => false,
        'company_name' => 'Cliente DuskTest S.A.',
        'is_customer' => true,
    ]);

    $pending = Invoice::factory()->create([
        'third_party_id' => $customer->id,
        'invoice_number' => 'FAC-PENDING-DUSK',
        'total_value' => 1500000,
        'issue_date' => Carbon::today()->subDays(5),
        'payment_status' => PaymentStatus::Pending,
    ]);
    $overdue = Invoice::factory()->create([
        'third_party_id' => $customer->id,
        'invoice_number' => 'FAC-OVERDUE-DUSK',
        'total_value' => 2500000,
        'issue_date' => Carbon::today()->subDays(30),
        'payment_status' => PaymentStatus::Overdue,
    ]);

    $this->browse(function (Browser $browser) use ($user, $pending, $overdue): void {
        $browser->loginAs($user)
            ->visit('/invoices')
            ->waitForText('Facturas')
            ->assertSee('Número')
            ->assertSee('Cliente')
            ->assertSee('Fecha Emisión')
            ->assertSee('Valor Total')
            ->assertSee('Estado')
            ->assertSee($pending->invoice_number)
            ->assertSee($overdue->invoice_number)
            ->assertDontSee('auto-generated by Blueprint')
            ->screenshot('invoices-index-rendered');

        // Apply the overdue filter — only the expired invoice remains
        $browser->visit('/invoices?filter[payment_status]=overdue')
            ->waitForText('Facturas')
            ->assertSee($overdue->invoice_number)
            ->assertDontSee($pending->invoice_number)
            ->assertSee('Vencido')
            ->screenshot('invoices-index-overdue-filter');
    });
});

test('invoices show page renders five cards and mark-paid transitions state', function (): void {
    $user = invoicesAuthenticateAsSuperAdmin();

    $customer = ThirdParty::factory()->create([
        'is_natural_person' => false,
        'company_name' => 'Cliente ShowTest S.A.',
        'is_customer' => true,
    ]);
    $invoice = Invoice::factory()->create([
        'third_party_id' => $customer->id,
        'invoice_number' => 'FAC-SHOW-001',
        'total_value' => 3750000,
        'issue_date' => Carbon::today()->subDays(10),
        'payment_status' => PaymentStatus::Pending,
        'notes' => 'Factura de prueba para el show.',
    ]);

    $this->browse(function (Browser $browser) use ($user, $invoice, $customer): void {
        $browser->loginAs($user)
            ->visit("/invoices/{$invoice->id}")
            ->waitForText($invoice->invoice_number)
            ->assertSee('Datos de la Factura')
            ->assertSee('Cliente')
            ->assertSee('Observaciones')
            ->assertSee('Servicios Facturados')
            ->assertSee($customer->company_name)
            ->assertSee('Ver tercero')
            ->assertSee('Pendiente')
            ->assertSee('Marcar como pagado')
            ->assertSee('Factura de prueba para el show.')
            ->assertDontSee('auto-generated by Blueprint')
            ->screenshot('invoices-show-five-cards')
            ->press('Marcar como pagado')
            ->waitForText('Pagado')
            ->assertDontSee('Marcar como pagado')
            ->screenshot('invoices-show-after-mark-paid');
    });
});

test('accounting user can CRUD invoices and cannot see Eliminar action', function (): void {
    $user = invoicesUserWithRole('accounting');

    $customer = ThirdParty::factory()->create([
        'is_natural_person' => false,
        'company_name' => 'Cliente AccTest S.A.',
        'is_customer' => true,
    ]);

    $invoice = Invoice::factory()->create([
        'third_party_id' => $customer->id,
        'invoice_number' => 'FAC-ACC-001',
        'total_value' => 1000000,
        'issue_date' => Carbon::today()->subDays(2),
        'payment_status' => PaymentStatus::Pending,
        'notes' => 'Factura existente para accounting.',
    ]);

    $this->browse(function (Browser $browser) use ($user, $invoice): void {
        $browser->loginAs($user)
            ->visit('/invoices')
            ->waitForText('Facturas')
            ->assertSee('Crear Factura')
            ->assertSee($invoice->invoice_number)
            ->assertDontSee('auto-generated by Blueprint')
            ->screenshot('invoices-accounting-index');

        // Accounting can open the edit modal from the row action menu
        // (UPDATE_INVOICES grant).
        $browser->visit('/invoices')
            ->waitForText($invoice->invoice_number)
            ->press('Abrir menú')
            ->waitFor('[role="menu"]')
            ->clickAtXPath("//*[@role='menuitem'][contains(., 'Editar')]")
            ->waitForText('Editar Factura')
            ->assertSee('Cliente')
            ->assertSee('Valor Total')
            ->assertDontSee('auto-generated by Blueprint')
            ->screenshot('invoices-accounting-edit');

        // Accounting is rejected on DELETE (no DELETE_INVOICES grant).
        // We can't easily click a delete button that isn't rendered, so
        // pin the authorization at the route layer via a direct POST to
        // the destroy endpoint is covered by the Pest suite; here we
        // assert the gated UI surface instead: the accounting session
        // sees Editar but NOT Eliminar in the page source. The
        // DataTableRowActions dropdown renders lazily, but the Eliminar
        // string only appears when onDelete is passed as a prop — which
        // the usePermissions hook in columns.tsx guards against.
        $browser->visit('/invoices')
            ->waitForText('Facturas')
            ->assertSourceMissing('Eliminar')
            ->screenshot('invoices-accounting-no-delete');
    });
});

test('operator receives 403 on invoices index', function (): void {
    $user = invoicesUserWithRole('operator');

    $this->browse(function (Browser $browser) use ($user): void {
        $browser->loginAs($user)
            ->visit('/invoices')
            ->assertSee('403')
            ->screenshot('invoices-operator-403');
    });
});
