<?php

use App\Enums\ServiceStatus;
use App\Models\Driver;
use App\Models\Service;
use App\Models\User;
use Illuminate\Support\Carbon;
use Laravel\Dusk\Browser;
use Spatie\Permission\Models\Role as SpatieRole;

/**
 * ENH-001 — UI regression for the Mapbox → Google Maps migration.
 *
 * Google's interactive map tiles are network-dependent and flaky inside
 * headless Selenium, so these assertions deliberately target SGTE's own
 * chrome (labels, dialogs, the static-map <img> `src`) and never the
 * Google-rendered map surface itself. Fixtures are built inline so the
 * tests don't depend on the full database seeder.
 */
beforeEach(function (): void {
    $this->artisan('migrate:fresh', ['--no-interaction' => true]);
});

function mapsSuperAdmin(): User
{
    $role = SpatieRole::firstOrCreate(['name' => 'super_admin', 'guard_name' => 'web']);
    $user = User::factory()->create();
    $user->assignRole($role);

    return $user;
}

test('service create form renders the LocationField and opens the Google map picker', function (): void {
    $user = mapsSuperAdmin();

    $this->browse(function (Browser $browser) use ($user): void {
        $browser->loginAs($user)
            ->visit('/services/create')
            ->waitForText('Crear Servicio')
            ->assertSee('Origen y Destino')
            // LocationField renders origin + destination address inputs
            // and the "Marcar en mapa" buttons, with no error banner.
            ->assertPresent('#origin_address')
            ->assertPresent('#destination_address')
            ->assertPresent('button[aria-label="Marcar en mapa"]')
            ->assertDontSee('auto-generated by Blueprint')
            ->screenshot('enh-001-service-form-location-field')
            // Opening the map picker shows the Google-backed dialog.
            ->click('button[aria-label="Marcar en mapa"]')
            ->waitForText('Marcar ubicación en el mapa')
            ->assertSee('Dirección visible para el conductor')
            ->screenshot('enh-001-service-form-map-picker');
    });
});

test('service detail page shows Google static-map previews instead of the placeholder', function (): void {
    $user = mapsSuperAdmin();
    $service = Service::factory()->create([
        'origin_coordinates' => '4.6679000,-74.0541000',
        'origin_coordinates_source' => 'google',
        'destination_coordinates' => '4.6291000,-74.0648000',
        'destination_coordinates_source' => 'google',
    ]);

    $this->browse(function (Browser $browser) use ($user, $service): void {
        $browser->loginAs($user)
            ->visit('/services/'.$service->id)
            ->waitForText('Detalle de la Ruta')
            // The labels render via CSS `uppercase`, so check the HTML
            // source (mixed-case in the DOM) rather than rendered text.
            ->assertSourceHas('Mapa del Origen')
            ->assertSourceHas('Mapa del Destino')
            ->assertSourceMissing('Mapa en desarrollo')
            // The static-map previews are <img>s pointing at the
            // Maps Static API.
            ->assertSourceHas('maps.googleapis.com/maps/api/staticmap')
            ->screenshot('enh-001-service-detail-static-maps');
    });
});

test('driver dashboard service cards show Google static-map previews', function (): void {
    $driverRole = SpatieRole::firstOrCreate(['name' => 'driver', 'guard_name' => 'web']);
    $driverUser = User::factory()->create();
    $driverUser->assignRole($driverRole);
    $driver = Driver::factory()->create(['user_id' => $driverUser->id]);

    Service::factory()->create([
        'driver_id' => $driver->id,
        'service_status' => ServiceStatus::Open,
        'service_date' => Carbon::today()->toDateString(),
        'origin_coordinates' => '4.6679000,-74.0541000',
        'origin_coordinates_source' => 'google',
        'destination_coordinates' => '4.6291000,-74.0648000',
        'destination_coordinates_source' => 'google',
    ]);

    $this->browse(function (Browser $browser) use ($driverUser): void {
        $browser->loginAs($driverUser)
            ->visit('/driver')
            ->waitForText('Mis Servicios')
            ->assertDontSee('auto-generated by Blueprint')
            ->assertSourceHas('maps.googleapis.com/maps/api/staticmap')
            ->screenshot('enh-001-driver-dashboard-static-maps');
    });
});
