<?php

use App\Models\Contract;
use App\Models\ThirdParty;
use App\Models\User;
use App\Models\Vehicle;
use Laravel\Dusk\Browser;
use Spatie\Permission\Models\Role as SpatieRole;

beforeEach(function (): void {
    $this->artisan('migrate:fresh', ['--no-interaction' => true]);
});

function thirdPartiesAuthenticateAsSuperAdmin(): User
{
    $role = SpatieRole::firstOrCreate(['name' => 'super_admin', 'guard_name' => 'web']);
    $user = User::where('email', env('SUPER_ADMIN_USER'))->first();
    if (! $user) {
        $user = User::factory()->create([
            'email' => env('SUPER_ADMIN_USER'),
            'password' => bcrypt(env('SUPER_ADMIN_PASSWORD')),
        ]);
    }
    $user->assignRole($role);

    return $user;
}

test('third parties index renders the table with Spanish headers and combines role filters', function (): void {
    $user = thirdPartiesAuthenticateAsSuperAdmin();

    $customerOnly = ThirdParty::factory()->create([
        'is_natural_person' => true,
        'first_name' => 'Pedro',
        'first_lastname' => 'CustomerOnly',
        'is_customer' => true,
        'is_provider' => false,
    ]);
    $providerOnly = ThirdParty::factory()->create([
        'is_natural_person' => false,
        'company_name' => 'Repuestos ProviderOnly Ltda',
        'is_customer' => false,
        'is_provider' => true,
    ]);
    $both = ThirdParty::factory()->create([
        'is_natural_person' => false,
        'company_name' => 'Transp. BothRoles S.A.',
        'is_customer' => true,
        'is_provider' => true,
    ]);

    $this->browse(function (Browser $browser) use (
        $user,
        $customerOnly,
        $providerOnly,
        $both,
    ): void {
        $browser->loginAs($user)
            ->visit('/third-parties')
            ->waitForText('Terceros')
            ->assertSee('Documento')
            ->assertSee('Nombre')
            ->assertSee('Tipo')
            ->assertSee('Roles')
            ->assertSee('Municipio')
            ->assertSee('Vinculación')
            ->assertSee($customerOnly->first_lastname)
            ->assertSee($providerOnly->company_name)
            ->assertSee($both->company_name)
            ->assertDontSee('auto-generated by Blueprint')
            ->screenshot('third-parties-index-rendered');

        // Apply both role filters set to "Sí" — only the "both" row remains
        $browser->visit('/third-parties?filter[is_customer]=1&filter[is_provider]=1')
            ->waitForText('Terceros')
            ->assertSee($both->company_name)
            ->assertDontSee($customerOnly->first_lastname)
            ->assertDontSee($providerOnly->company_name)
            ->screenshot('third-parties-index-both-roles');
    });
});

test('show page customer-only path renders Contratos but not Vehiculos', function (): void {
    $user = thirdPartiesAuthenticateAsSuperAdmin();

    $customer = ThirdParty::factory()->create([
        'is_natural_person' => false,
        'company_name' => 'Cliente Solo S.A.',
        'is_customer' => true,
        'is_provider' => false,
    ]);

    Contract::factory()->count(2)->create([
        'third_party_id' => $customer->id,
    ]);

    $this->browse(function (Browser $browser) use ($user, $customer): void {
        $browser->loginAs($user)
            ->visit("/third-parties/{$customer->id}")
            ->waitForText($customer->company_name)
            ->assertSee('Información General')
            ->assertSee('Datos de Contacto')
            ->assertSee('Contratos')
            ->assertDontSee('Vehículos del Tercero')
            ->assertDontSee('auto-generated by Blueprint')
            ->screenshot('third-party-show-customer-only');
    });
});

test('show page provider-only path renders Vehiculos but not Contratos', function (): void {
    $user = thirdPartiesAuthenticateAsSuperAdmin();

    $provider = ThirdParty::factory()->create([
        'is_natural_person' => false,
        'company_name' => 'Proveedor Solo Ltda',
        'is_customer' => false,
        'is_provider' => true,
    ]);

    Vehicle::factory()->count(2)->create([
        'is_third_party' => true,
        'third_party_id' => $provider->id,
    ]);

    $this->browse(function (Browser $browser) use ($user, $provider): void {
        $browser->loginAs($user)
            ->visit("/third-parties/{$provider->id}")
            ->waitForText($provider->company_name)
            ->assertSee('Información General')
            ->assertSee('Datos de Contacto')
            ->assertSee('Vehículos del Tercero')
            ->assertDontSee('Contratos (')
            ->assertDontSee('auto-generated by Blueprint')
            ->screenshot('third-party-show-provider-only');
    });
});

test('vehicle show Ver tercero link lands on the rebuilt third-party show page', function (): void {
    $user = thirdPartiesAuthenticateAsSuperAdmin();

    $owner = ThirdParty::factory()->create([
        'is_natural_person' => false,
        'company_name' => 'Dueño del Vehículo S.A.',
        'is_customer' => false,
        'is_provider' => true,
    ]);
    $vehicle = Vehicle::factory()->create([
        'is_third_party' => true,
        'third_party_id' => $owner->id,
    ]);

    $this->browse(function (Browser $browser) use ($user, $vehicle, $owner): void {
        $browser->loginAs($user)
            ->visit("/vehicles/{$vehicle->id}")
            ->waitForText($vehicle->plate)
            ->assertSee('Ver tercero')
            ->clickLink('Ver tercero')
            ->waitForLocation("/third-parties/{$owner->id}")
            ->assertPathIs("/third-parties/{$owner->id}")
            ->assertSee($owner->company_name)
            ->assertDontSee('auto-generated by Blueprint')
            ->screenshot('vehicle-to-third-party-cross-link');
    });
});
