<?php

use App\Models\Driver;
use App\Models\Municipality;
use App\Models\Service;
use App\Models\ThirdParty;
use App\Models\User;
use App\Models\Vehicle;
use Illuminate\Support\Carbon;
use Laravel\Dusk\Browser;
use Spatie\Permission\Models\Role as SpatieRole;

beforeEach(function (): void {
    // We bring up only the schema + the catalog data migration (which
    // runs in all environments and creates the role/permission set we
    // need for super-admin login). Skipping --seed avoids the
    // operational seeders, which need an idempotent fixture setup we
    // build per-test below.
    $this->artisan('migrate:fresh', ['--no-interaction' => true]);
});

function vehiclesAuthenticateAsSuperAdmin(): User
{
    $role = SpatieRole::firstOrCreate(['name' => 'super_admin', 'guard_name' => 'web']);
    $user = User::where('email', env('SUPER_ADMIN_USER'))->first();
    if (! $user) {
        $user = User::factory()->create([
            'email' => env('SUPER_ADMIN_USER'),
            'password' => bcrypt(env('SUPER_ADMIN_PASSWORD')),
        ]);
    }
    $user->assignRole($role);

    return $user;
}

/**
 * Seeds three vehicles in mixed expiry states so the docs_status filter
 * has something meaningful to filter on.
 *
 * @return array{expired: Vehicle, expiring: Vehicle, ok: Vehicle}
 */
function vehiclesSeedMixedExpiry(): array
{
    $today = Carbon::today();
    $municipality = Municipality::factory()->create();

    $expired = Vehicle::factory()->create([
        'plate' => 'EXP100',
        'internal_code' => 'V-EXP',
        'is_third_party' => false,
        'municipality_id' => $municipality->id,
        'soat_due_date' => $today->copy()->subDay(),
        'rtm_due_date' => $today->copy()->addYear(),
        'operation_card_due_date' => $today->copy()->addYear(),
    ]);

    $expiring = Vehicle::factory()->create([
        'plate' => 'WRN200',
        'internal_code' => 'V-WRN',
        'is_third_party' => false,
        'municipality_id' => $municipality->id,
        'soat_due_date' => $today->copy()->addDays(15),
        'rtm_due_date' => $today->copy()->addYear(),
        'operation_card_due_date' => $today->copy()->addYear(),
    ]);

    $ok = Vehicle::factory()->create([
        'plate' => 'OKK300',
        'internal_code' => 'V-OKK',
        'is_third_party' => false,
        'municipality_id' => $municipality->id,
        'soat_due_date' => $today->copy()->addYears(1),
        'rtm_due_date' => $today->copy()->addYears(1),
        'operation_card_due_date' => $today->copy()->addYears(1),
    ]);

    return ['expired' => $expired, 'expiring' => $expiring, 'ok' => $ok];
}

test('vehicles index renders the table with Spanish headers and expected rows', function (): void {
    $user = vehiclesAuthenticateAsSuperAdmin();
    $vehicles = vehiclesSeedMixedExpiry();

    $this->browse(function (Browser $browser) use ($user, $vehicles): void {
        $browser->loginAs($user)
            ->visit('/vehicles')
            ->waitForText('Vehículos')
            ->assertSee('Vehículos')
            ->assertSee('Placa')
            ->assertSee('Cód. Interno')
            ->assertSee('Tipo')
            ->assertSee('Propietario')
            ->assertSee('Estado')
            ->assertSee('Documentos')
            ->assertSee($vehicles['expired']->plate)
            ->assertSee($vehicles['expiring']->plate)
            ->assertSee($vehicles['ok']->plate)
            ->assertDontSee('Drivers Index')
            ->assertDontSee('auto-generated by Blueprint')
            ->screenshot('vehicles-index-rendered');
    });
});

test('vehicles index docs_status=expired filter narrows to expired rows', function (): void {
    $user = vehiclesAuthenticateAsSuperAdmin();
    $vehicles = vehiclesSeedMixedExpiry();

    $this->browse(function (Browser $browser) use ($user, $vehicles): void {
        $browser->loginAs($user)
            ->visit('/vehicles?filter[docs_status]=expired')
            ->waitForText('Vehículos')
            ->assertSee($vehicles['expired']->plate)
            ->assertDontSee($vehicles['expiring']->plate)
            ->assertDontSee($vehicles['ok']->plate)
            ->screenshot('vehicles-index-filtered-expired');
    });
});

test('dashboard alert row links into the filtered vehicles index', function (): void {
    $user = vehiclesAuthenticateAsSuperAdmin();
    $vehicles = vehiclesSeedMixedExpiry();

    $this->browse(function (Browser $browser) use ($user, $vehicles): void {
        $browser->loginAs($user)
            ->visit('/dashboard')
            ->waitForText('Alertas de documentos')
            ->assertSee('Alertas de documentos')
            ->assertSee($vehicles['expired']->plate)
            ->screenshot('dashboard-with-alerts')
            ->clickLink($vehicles['expired']->plate)
            ->waitForLocation('/vehicles')
            ->assertPathIs('/vehicles');

        // assertQueryStringHas can't parse Laravel's bracket notation
        // (it treats `filter[docs_status]` as a string key after
        // parse_str expansion), so we read the URL directly and assert
        // the relevant substring is present.
        $currentUrl = $browser->driver->getCurrentURL();
        expect($currentUrl)
            ->toContain('filter')
            ->toContain('docs_status')
            ->toContain('expired');

        $browser
            ->assertSee($vehicles['expired']->plate)
            ->assertDontSee($vehicles['ok']->plate)
            ->screenshot('vehicles-after-dashboard-cross-link');
    });
});

test('vehicle show page renders five sections with rich data', function (): void {
    $user = vehiclesAuthenticateAsSuperAdmin();

    $municipality = Municipality::factory()->create();
    $thirdParty = ThirdParty::factory()->create([
        'company_name' => 'Transportes Demo S.A.',
        'is_natural_person' => false,
    ]);
    $vehicle = Vehicle::factory()->create([
        'plate' => 'SHW001',
        'internal_code' => 'V-SHW',
        'brand' => 'Chevrolet',
        'line' => 'NPR',
        'model_year' => 2024,
        'capacity' => 30,
        'municipality_id' => $municipality->id,
        'is_third_party' => true,
        'third_party_id' => $thirdParty->id,
        'soat_due_date' => Carbon::today()->addMonths(6),
        'rtm_due_date' => Carbon::today()->addMonths(6),
        'operation_card_due_date' => Carbon::today()->addMonths(6),
    ]);

    Driver::factory()->count(1)->create();
    Service::factory()->count(5)->create([
        'vehicle_id' => $vehicle->id,
    ]);

    $this->browse(function (Browser $browser) use ($user, $vehicle): void {
        $browser->loginAs($user)
            ->visit("/vehicles/{$vehicle->id}")
            ->waitForText($vehicle->plate)
            ->assertSee($vehicle->plate)
            ->assertSee($vehicle->internal_code)
            ->assertSee('Información General')
            ->assertSee('Documentos')
            ->assertSee('Propietario')
            ->assertSee('Servicios Recientes')
            ->assertSee('Transportes Demo S.A.')
            ->assertSee('Chevrolet')
            ->assertSee('NPR')
            ->assertDontSee('auto-generated by Blueprint')
            ->screenshot('vehicle-show-rendered');
    });
});

test('admin opens the create modal and sees the form fields', function (): void {
    $user = vehiclesAuthenticateAsSuperAdmin();
    Municipality::factory()->create();

    $this->browse(function (Browser $browser) use ($user): void {
        $browser->loginAs($user)
            ->visit('/vehicles')
            ->waitForText('Vehículos')
            ->press('Crear Vehículo')
            ->waitForText('Complete los campos para registrar un nuevo vehículo')
            ->assertSee('Crear Vehículo')
            ->assertSee('Complete los campos para registrar un nuevo vehículo')
            ->assertSee('Placa')
            ->assertSee('Marca')
            ->assertSee('Línea')
            ->assertSee('SOAT')
            ->assertSee('RTM')
            ->screenshot('vehicles-create-modal-open');

        // Driving every field through Radix Select + MunicipalityCombobox
        // is brittle in Dusk; the persistence path is fully covered by
        // VehicleControllerTest::test_store_saves_and_redirects (Pest).
        // What this Dusk scenario pins is "the index button opens the
        // modal with the right form scaffolding visible" — the regression
        // we're guarding against is the Blueprint scaffold returning.
    });
});
