<?php

use Illuminate\Support\Facades\File;

beforeEach(function () {
    $this->outputPath = sys_get_temp_dir().'/enums-test-'.uniqid();
});

afterEach(function () {
    File::deleteDirectory($this->outputPath);
});

test('enum:typescript generates typescript files for all string-backed enums', function () {
    $this->artisan('enum:typescript', ['--output' => $this->outputPath])
        ->assertSuccessful();

    expect(File::exists($this->outputPath.'/Permission.ts'))->toBeTrue()
        ->and(File::exists($this->outputPath.'/Role.ts'))->toBeTrue()
        ->and(File::exists($this->outputPath.'/index.ts'))->toBeTrue();
});

test('generated permission file contains const object and type', function () {
    $this->artisan('enum:typescript', ['--output' => $this->outputPath]);

    $content = File::get($this->outputPath.'/Permission.ts');

    expect($content)
        ->toContain('export const Permission = {')
        ->toContain("VIEW_DASHBOARD: 'dashboard.view',")
        ->toContain('} as const;')
        ->toContain('export type Permission = (typeof Permission)[keyof typeof Permission];');
});

test('generated file includes labels when enum has label method', function () {
    $this->artisan('enum:typescript', ['--output' => $this->outputPath]);

    $content = File::get($this->outputPath.'/Permission.ts');

    expect($content)
        ->toContain('export const PermissionLabel: Record<Permission, string> = {')
        ->toContain("'dashboard.view': 'Ver dashboard',");
});

test('generated role file has correct structure', function () {
    $this->artisan('enum:typescript', ['--output' => $this->outputPath]);

    $content = File::get($this->outputPath.'/Role.ts');

    expect($content)
        ->toContain("SUPER_ADMIN: 'super_admin',")
        ->toContain('export const RoleLabel: Record<Role, string> = {')
        ->toContain("'super_admin': 'Super Administrador',");
});

test('generated index file re-exports all enums', function () {
    $this->artisan('enum:typescript', ['--output' => $this->outputPath]);

    $content = File::get($this->outputPath.'/index.ts');

    expect($content)
        ->toContain("export * from './Permission';")
        ->toContain("export * from './Role';");
});

test('generated files include auto-generated header comment', function () {
    $this->artisan('enum:typescript', ['--output' => $this->outputPath]);

    $content = File::get($this->outputPath.'/Permission.ts');

    expect($content)->toStartWith("// This file is auto-generated by `php artisan enum:typescript`\n// Do not edit manually.");
});
