<?php

namespace Tests\Feature\Services\Imports;

use App\Enums\Role;
use App\Models\DataImport;
use App\Models\User;
use App\Services\Imports\UserImporter;
use Illuminate\Support\Facades\Hash;
use Spatie\SimpleExcel\SimpleExcelReader;
use Spatie\SimpleExcel\SimpleExcelWriter;

function importerFor(): UserImporter
{
    return app(UserImporter::class);
}

function runImporter(UserImporter $importer, DataImport $import, string $csv): array
{
    $tmp = tempnam(sys_get_temp_dir(), 'imp_test_').'.csv';
    file_put_contents($tmp, $csv);

    $errorsTmp = tempnam(sys_get_temp_dir(), 'errs_').'.csv';
    $errorsWriter = SimpleExcelWriter::create($errorsTmp);
    $errorsWriter->addHeader(['row_number', 'error_message', 'original_data']);

    $reader = SimpleExcelReader::create($tmp);
    $counters = ['created' => 0, 'updated' => 0, 'skipped' => 0, 'errored' => 0];

    $importer->processFile($reader, $import, $errorsWriter, function (array $delta) use (&$counters): void {
        foreach ($delta as $key => $value) {
            $counters[$key] += $value;
        }
    });

    $reader->close();
    $errorsWriter->close();

    $errorsContents = file_get_contents($errorsTmp);
    @unlink($tmp);
    @unlink($errorsTmp);

    return ['counters' => $counters, 'errors' => $errorsContents];
}

beforeEach(function (): void {
    foreach (Role::cases() as $role) {
        \Spatie\Permission\Models\Role::firstOrCreate(['name' => $role->value, 'guard_name' => 'web']);
    }
});

test('valid header passes', function (): void {
    $importer = importerFor();
    $tmp = tempnam(sys_get_temp_dir(), 'h_').'.csv';
    file_put_contents($tmp, "email,name,role,password\n");

    $check = $importer->validateHeader($tmp);

    expect($check->ok)->toBeTrue();
    @unlink($tmp);
});

test('header missing columns is rejected with a clear message', function (): void {
    $importer = importerFor();
    $tmp = tempnam(sys_get_temp_dir(), 'h_').'.csv';
    file_put_contents($tmp, "email,name\n");

    $check = $importer->validateHeader($tmp);

    expect($check->ok)->toBeFalse();
    expect($check->error)->toContain('role');
    expect($check->error)->toContain('password');
    @unlink($tmp);
});

test('countRows for csv discounts the header', function (): void {
    $importer = importerFor();
    $tmp = tempnam(sys_get_temp_dir(), 'h_').'.csv';
    file_put_contents($tmp, "email,name,role,password\nA,B,admin,\nC,D,operator,\nE,F,driver,\n");

    expect($importer->countRows($tmp))->toBe(3);
    @unlink($tmp);
});

test('valid row creates a user with autogenerated password and must_change_password=true', function (): void {
    $import = DataImport::factory()->create();
    $csv = "email,name,role,password\njohn@cliente.co,John Doe,admin,\n";

    $result = runImporter(importerFor(), $import, $csv);

    expect($result['counters'])->toBe(['created' => 1, 'updated' => 0, 'skipped' => 0, 'errored' => 0]);

    $user = User::query()->where('email', 'john@cliente.co')->first();
    expect($user)->not->toBeNull();
    expect($user->must_change_password)->toBeTrue();
    expect($user->hasRole(Role::ADMIN))->toBeTrue();
});

test('explicit password keeps must_change_password=false', function (): void {
    $import = DataImport::factory()->create();
    $csv = "email,name,role,password\njane@cliente.co,Jane,operator,Temporal2026!\n";

    runImporter(importerFor(), $import, $csv);

    $user = User::query()->where('email', 'jane@cliente.co')->first();
    expect($user)->not->toBeNull();
    expect($user->must_change_password)->toBeFalse();
    expect(Hash::check('Temporal2026!', $user->password))->toBeTrue();
});

test('existing email is skipped when update_existing=false', function (): void {
    $import = DataImport::factory()->create(['update_existing' => false]);
    User::factory()->create(['email' => 'duplicate@cliente.co', 'name' => 'Original']);

    $csv = "email,name,role,password\nduplicate@cliente.co,Updated,operator,\n";
    $result = runImporter(importerFor(), $import, $csv);

    expect($result['counters'])->toBe(['created' => 0, 'updated' => 0, 'skipped' => 1, 'errored' => 0]);
    expect(User::query()->where('email', 'duplicate@cliente.co')->first()->name)->toBe('Original');
});

test('existing email is updated when update_existing=true', function (): void {
    $import = DataImport::factory()->create(['update_existing' => true]);
    $existing = User::factory()->create(['email' => 'duplicate@cliente.co', 'name' => 'Original']);
    $existing->assignRole(Role::ADMIN->value);

    $csv = "email,name,role,password\nduplicate@cliente.co,Updated Name,operator,\n";
    $result = runImporter(importerFor(), $import, $csv);

    expect($result['counters'])->toBe(['created' => 0, 'updated' => 1, 'skipped' => 0, 'errored' => 0]);
    $fresh = User::query()->where('email', 'duplicate@cliente.co')->first();
    expect($fresh->name)->toBe('Updated Name');
    expect($fresh->hasRole(Role::OPERATOR))->toBeTrue();
});

test('super_admin role is rejected through the import path', function (): void {
    $import = DataImport::factory()->create();
    $csv = "email,name,role,password\nbad@cliente.co,Bad,super_admin,\n";

    $result = runImporter(importerFor(), $import, $csv);

    expect($result['counters']['errored'])->toBe(1);
    expect($result['counters']['created'])->toBe(0);
    expect(User::query()->where('email', 'bad@cliente.co')->exists())->toBeFalse();
});

test('duplicate email within the same file is reported once', function (): void {
    $import = DataImport::factory()->create();
    $csv = "email,name,role,password\nx@cliente.co,X,admin,\nx@cliente.co,Y,admin,\n";

    $result = runImporter(importerFor(), $import, $csv);

    expect($result['counters']['created'])->toBe(1);
    expect($result['counters']['errored'])->toBe(1);
    expect($result['errors'])->toContain('Clave duplicada');
});

test('dry_run does not persist users but counts what would happen', function (): void {
    $import = DataImport::factory()->dryRun()->create();
    User::factory()->create(['email' => 'existing@cliente.co']);

    $csv = "email,name,role,password\nnew@cliente.co,New,admin,\nexisting@cliente.co,Old,admin,\n";
    $result = runImporter(importerFor(), $import, $csv);

    // dry_run + update_existing=false → existing is "skipped", new is "created" (counted, not persisted)
    expect($result['counters']['created'])->toBe(1);
    expect($result['counters']['skipped'])->toBe(1);
    expect(User::query()->where('email', 'new@cliente.co')->exists())->toBeFalse();
});

test('invalid email format goes to errored', function (): void {
    $import = DataImport::factory()->create();
    $csv = "email,name,role,password\nnotanemail,Bad,admin,\n";

    $result = runImporter(importerFor(), $import, $csv);

    expect($result['counters']['errored'])->toBe(1);
    expect($result['counters']['created'])->toBe(0);
});

test('missing required field goes to errored', function (): void {
    $import = DataImport::factory()->create();
    $csv = "email,name,role,password\nuser@cliente.co,,admin,\n";

    $result = runImporter(importerFor(), $import, $csv);

    expect($result['counters']['errored'])->toBe(1);
    expect($result['errors'])->toContain('nombre');
});

test('expected headers and natural key', function (): void {
    $importer = importerFor();
    expect($importer->expectedHeaders())->toBe(['email', 'name', 'role', 'password']);
    expect($importer->naturalKey())->toBe('email');
});
