[unix_http_server]
file=/var/run/supervisor.sock
chmod=0770
chown=root:app

[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock

[program:octane]
command=/usr/local/bin/php artisan octane:start --server=frankenphp --host=0.0.0.0 --port=8000 --workers=auto --max-requests=1000
user=app
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0

[program:horizon]
process_name=%(program_name)s
command=/usr/local/bin/php artisan horizon
user=app
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stopwaitsecs=3600

[program:reverb]
process_name=%(program_name)s
command=/usr/local/bin/php artisan reverb:start --host=0.0.0.0 --port=8080
user=app
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stopwaitsecs=3600

[program:ssr]
process_name=%(program_name)s
command=/usr/local/bin/php artisan inertia:start-ssr
user=app
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0

[program:scheduler]
process_name=%(program_name)s
command=/usr/local/bin/php artisan schedule:work
user=app
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
