import { Head } from '@inertiajs/react';
import AppLayout from '@/layouts/app-layout';
import documentTypes from '@/routes/document-types';
import { type BreadcrumbItem } from '@/types';

// TODO: Replace with your actual breadcrumb setup
const breadcrumbs: BreadcrumbItem[] = [
    {
        title: 'Document-Types Show',
        href: documentTypes.show().url,
    },
];

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export default function DocumentTypesShow({
    documentType,
}: {
    documentType: any;
}) {
    return (
        <AppLayout breadcrumbs={breadcrumbs}>
            <Head title="Document-Types Show" />
            <div className="flex h-full flex-1 flex-col gap-4 rounded-xl p-4">
                <div className="relative min-h-screen flex-1 overflow-hidden rounded-xl border border-sidebar-border bg-background p-6 md:min-h-min dark:border-sidebar-border">
                    <h1 className="text-2xl font-bold">Document-Types Show</h1>
                    <p className="mt-4 text-muted-foreground">
                        This component was auto-generated by Blueprint.
                    </p>
                    <pre className="mt-4 overflow-auto rounded-lg bg-muted p-4 text-sm">
                        {JSON.stringify({ documentType }, null, 2)}
                    </pre>
                </div>
            </div>
        </AppLayout>
    );
}
