// This file is auto-generated by `php artisan enum:typescript`
// Do not edit manually.

export const BillingGroup = {
    Salud: 'salud',
    Escolar: 'escolar',
    Turismo: 'turismo',
    Empresarial: 'empresarial',
    Ocasional: 'ocasional',
} as const;

export type BillingGroup = (typeof BillingGroup)[keyof typeof BillingGroup];

export const BillingGroupLabel: Record<BillingGroup, string> = {
    salud: 'Salud',
    escolar: 'Escolar',
    turismo: 'Turismo',
    empresarial: 'Empresarial',
    ocasional: 'Ocasional',
};
