// This file is auto-generated by `php artisan enum:typescript`
// Do not edit manually.

export const BillingUnitType = {
    Viaje: 'viaje',
    Pasajero: 'pasajero',
    Dia: 'dia',
    Hora: 'hora',
} as const;

export type BillingUnitType =
    (typeof BillingUnitType)[keyof typeof BillingUnitType];

export const BillingUnitTypeLabel: Record<BillingUnitType, string> = {
    viaje: 'Viaje',
    pasajero: 'Pasajero',
    dia: 'Día',
    hora: 'Hora',
};
