// This file is auto-generated by `php artisan enum:typescript`
// Do not edit manually.

export const ContractObject = {
    Business: 'business',
    Tourism: 'tourism',
    Health: 'health',
    Occasional: 'occasional',
} as const;

export type ContractObject =
    (typeof ContractObject)[keyof typeof ContractObject];

export const ContractObjectLabel: Record<ContractObject, string> = {
    business: 'Empresarial',
    tourism: 'Turismo',
    health: 'Salud',
    occasional: 'Ocasional',
};
