// This file is auto-generated by `php artisan enum:typescript`
// Do not edit manually.

export const DataImportType = {
    Users: 'users',
    ThirdParties: 'third_parties',
    Drivers: 'drivers',
    Vehicles: 'vehicles',
} as const;

export type DataImportType = (typeof DataImportType)[keyof typeof DataImportType];

export const DataImportTypeLabel: Record<DataImportType, string> = {
    'users': 'Usuarios',
    'third_parties': 'Terceros',
    'drivers': 'Conductores',
    'vehicles': 'Vehículos',
};
