// This file is auto-generated by `php artisan enum:typescript`
// Do not edit manually.

export const DataImportStatus = {
    Queued: 'queued',
    Processing: 'processing',
    Completed: 'completed',
    Failed: 'failed',
} as const;

export type DataImportStatus =
    (typeof DataImportStatus)[keyof typeof DataImportStatus];

export const DataImportStatusLabel: Record<DataImportStatus, string> = {
    queued: 'En cola',
    processing: 'Procesando',
    completed: 'Completado',
    failed: 'Falló',
};
