// This file is auto-generated by `php artisan enum:typescript`
// Do not edit manually.

export const DayStatusEnum = {
    Projected: 'projected',
    Executed: 'executed',
} as const;

export type DayStatusEnum = (typeof DayStatusEnum)[keyof typeof DayStatusEnum];

export const DayStatusEnumLabel: Record<DayStatusEnum, string> = {
    projected: 'Proyectado',
    executed: 'Ejecutado',
};
