// This file is auto-generated by `php artisan enum:typescript`
// Do not edit manually.

export const FuecStatus = {
    Active: 'active',
    Cancelled: 'cancelled',
} as const;

export type FuecStatus = (typeof FuecStatus)[keyof typeof FuecStatus];

export const FuecStatusLabel: Record<FuecStatus, string> = {
    active: 'Activo',
    cancelled: 'Cancelado',
};
