// This file is auto-generated by `php artisan enum:typescript`
// Do not edit manually.

export const IncidentSeverity = {
    Informational: 'informational',
    Minor: 'minor',
    Major: 'major',
} as const;

export type IncidentSeverity =
    (typeof IncidentSeverity)[keyof typeof IncidentSeverity];

export const IncidentSeverityLabel: Record<IncidentSeverity, string> = {
    informational: 'Informativo',
    minor: 'Menor',
    major: 'Mayor',
};
