// This file is auto-generated by `php artisan enum:typescript`
// Do not edit manually.

export const LicenseCategory = {
    C1: 'C1',
    C2: 'C2',
    C3: 'C3',
} as const;

export type LicenseCategory = (typeof LicenseCategory)[keyof typeof LicenseCategory];

export const LicenseCategoryLabel: Record<LicenseCategory, string> = {
    'C1': 'C1',
    'C2': 'C2',
    'C3': 'C3',
};
