// This file is auto-generated by `php artisan enum:typescript`
// Do not edit manually.

export const PaymentMethod = {
    Cash: 'cash',
    Credit: 'credit',
    Transfer: 'transfer',
} as const;

export type PaymentMethod = (typeof PaymentMethod)[keyof typeof PaymentMethod];

export const PaymentMethodLabel: Record<PaymentMethod, string> = {
    cash: 'Efectivo',
    credit: 'Crédito',
    transfer: 'Transferencia',
};
