// This file is auto-generated by `php artisan enum:typescript`
// Do not edit manually.

export const PaymentStatus = {
    Pending: 'pending',
    Paid: 'paid',
    Overdue: 'overdue',
} as const;

export type PaymentStatus = (typeof PaymentStatus)[keyof typeof PaymentStatus];

export const PaymentStatusLabel: Record<PaymentStatus, string> = {
    pending: 'Pendiente',
    paid: 'Pagado',
    overdue: 'Vencido',
};
