// This file is auto-generated by `php artisan enum:typescript`
// Do not edit manually.

export const PermissionGroup = {
    DASHBOARD_SETTINGS: 'dashboard',
    VEHICLES: 'vehicles',
    DRIVERS: 'drivers',
    THIRD_PARTIES: 'third-parties',
    CONTRACTS: 'contracts',
    SERVICES: 'services',
    DAY_SUMMARY: 'day-summary',
    INCIDENTS: 'incidents',
    INVOICES: 'invoices',
    REPORTS: 'reports',
    FUEC: 'fuec',
    GPS: 'gps',
    USERS: 'users',
    INCIDENT_TYPES: 'incident-types',
    BILLING_GROUPS: 'billing-groups',
    CATALOGS: 'catalogs',
    AUDIT: 'audit',
    DATA_IMPORTS: 'data-imports',
    NOTIFICATIONS: 'notifications',
} as const;

export type PermissionGroup = (typeof PermissionGroup)[keyof typeof PermissionGroup];

export const PermissionGroupLabel: Record<PermissionGroup, string> = {
    'dashboard': 'Panel y Configuración',
    'vehicles': 'Vehículos',
    'drivers': 'Conductores',
    'third-parties': 'Terceros',
    'contracts': 'Contratos',
    'services': 'Servicios',
    'day-summary': 'Resumen del día',
    'incidents': 'Novedades',
    'invoices': 'Facturas',
    'reports': 'Reportes',
    'fuec': 'FUEC',
    'gps': 'GPS',
    'users': 'Usuarios',
    'incident-types': 'Tipos de novedad',
    'billing-groups': 'Grupos de facturación',
    'catalogs': 'Catálogos',
    'audit': 'Auditoría',
    'data-imports': 'Importaciones',
    'notifications': 'Notificaciones',
};
