// This file is auto-generated by `php artisan enum:typescript`
// Do not edit manually.

export const Role = {
    SUPER_ADMIN: 'super_admin',
    ADMIN: 'admin',
    OPERATOR: 'operator',
    DRIVER: 'driver',
    ACCOUNTING: 'accounting',
} as const;

export type Role = (typeof Role)[keyof typeof Role];

export const RoleLabel: Record<Role, string> = {
    'super_admin': 'Super Administrador',
    'admin': 'Administrador',
    'operator': 'Operación',
    'driver': 'Conductor',
    'accounting': 'Contabilidad',
};
