// This file is auto-generated by `php artisan enum:typescript`
// Do not edit manually.

export const ServiceStatus = {
    Open: 'open',
    Closed: 'closed',
} as const;

export type ServiceStatus = (typeof ServiceStatus)[keyof typeof ServiceStatus];

export const ServiceStatusLabel: Record<ServiceStatus, string> = {
    open: 'Abierto',
    closed: 'Cerrado',
};
