// This file is auto-generated by `php artisan enum:typescript`
// Do not edit manually.

export const VehicleStatus = {
    Active: 'active',
    Maintenance: 'maintenance',
    Retired: 'retired',
} as const;

export type VehicleStatus = (typeof VehicleStatus)[keyof typeof VehicleStatus];

export const VehicleStatusLabel: Record<VehicleStatus, string> = {
    'active': 'Activo',
    'maintenance': 'En Mantenimiento',
    'retired': 'Retirado',
};
