// This file is auto-generated by `php artisan enum:typescript`
// Do not edit manually.

export const VehicleType = {
    Bus: 'bus',
    Buseta: 'buseta',
    Van: 'van',
    Automobile: 'automobile',
} as const;

export type VehicleType = (typeof VehicleType)[keyof typeof VehicleType];

export const VehicleTypeLabel: Record<VehicleType, string> = {
    bus: 'Bus',
    buseta: 'Buseta',
    van: 'Van',
    automobile: 'Automóvil',
};
