import { Head } from '@inertiajs/react';
import AppLayout from '@/layouts/app-layout';
import serviceIncidents from '@/routes/service-incidents';
import { type BreadcrumbItem } from '@/types';

// TODO: Replace with your actual breadcrumb setup
const breadcrumbs: BreadcrumbItem[] = [
    {
        title: 'Service-Incidents Create',
        href: serviceIncidents.create().url,
    },
];

export default function ServiceIncidentsCreate() {
    return (
        <AppLayout breadcrumbs={breadcrumbs}>
            <Head title="Service-Incidents Create" />
            <div className="flex h-full flex-1 flex-col gap-4 rounded-xl p-4">
                <div className="relative min-h-screen flex-1 overflow-hidden rounded-xl border border-sidebar-border bg-background p-6 md:min-h-min dark:border-sidebar-border">
                    <h1 className="text-2xl font-bold">
                        Service-Incidents Create
                    </h1>
                    <p className="mt-4 text-muted-foreground">
                        This component was auto-generated by Blueprint.
                    </p>
                    <pre className="mt-4 overflow-auto rounded-lg bg-muted p-4 text-sm">
                        {JSON.stringify({}, null, 2)}
                    </pre>
                </div>
            </div>
        </AppLayout>
    );
}
